### ISSUE TITLE
Don't mix tabs and spaces

### ISSUE THREAD

**Issue by geary** [charlieh0tel/seveneleven#2]
The various source files are indented with a mix of leading tabs followed by spaces, and assume that the tabs are displayed as eight spaces. Many developers have their editors set to display tabs with a different width, often four spaces.

Mixing tabs and spaces leads to incorrect visual indentation as seen in this screenshot:

![image](https://user-images.githubusercontent.com/21968/77834921-aed21480-7105-11ea-9e2a-640452d53c48.png)

It would be better if the code used only tabs or only spaces for indentation. I didn't submit a PR because I don't know which you prefer. Generally I prefer tabs, but the code in each language uses column alignment in addition to indentation, so spaces would likely be preferred for that reason.

I know this is only a fun toy project, just helping with a nitpick on a common formatting problem. ;-)

**Comment by charlieh0tel** [comment]
I don't have emacs set up correctly on this new computer.   We don't do tabs at Google so that's how I roll.

I'll fix it.

**Comment by charlieh0tel** [comment]
Fixed.

**Comment by geary** [comment]
Thanks! Much easier to read the code now. :-)
